//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerServiceWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginDetail
    {
        public int Login_Userid { get; set; }
        public string Login_UserName { get; set; }
        public string Login_Password { get; set; }
    }
}
