//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerServiceWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalDataDetail
    {
        public int Person_ID { get; set; }
        public string Person_Name { get; set; }
        public int Person_Age { get; set; }
        public string Person_Occupation { get; set; }
        public string Person_Mail { get; set; }
    }
}
